pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building with a Jenkins Trigger..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing with a Jenkins Trigger..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying with a Jenkins Trigger444....'
            }
        }
	stage('gitlab') {
             steps {
             	echo 'Notify GitLab'
             	updateGitlabCommitStatus name: 'build', state: 'pending'
             	updateGitlabCommitStatus name: 'build', state: 'success'
          }
       }
    }
}
